{
  "Header": {
    "Original": "CVE-2022-30284 (In the python-libnmap package through 0.7.2 for Python, remote command ...)",
    "Line": 86623,
    "ID": "CVE-2022-30284",
    "Description": "(In the python-libnmap package through 0.7.2 for Python, remote command ...)"
  },
  "Annotations": [
    {
      "Original": "NOTE: Bogus python-libnmap issue",
      "Line": 86624,
      "Type": "NOTE",
      "Description": "Bogus python-libnmap issue"
    }
  ]
}