{
  "Header": {
    "Original": "CVE-2021-28678 (An issue was discovered in Pillow before 8.2.0. For BLP data, BlpImage ...)",
    "Line": 162762,
    "ID": "CVE-2021-28678",
    "Description": "(An issue was discovered in Pillow before 8.2.0. For BLP data, BlpImage ...)"
  },
  "Annotations": [
    {
      "Original": "[experimental] - pillow 8.2.0-1",
      "Line": 162763,
      "Type": "package",
      "Release": "experimental",
      "Package": "pillow",
      "Kind": "fixed",
      "Version": "8.2.0-1"
    },
    {
      "Original": "- pillow 8.1.2+dfsg-0.2 (bug #989062)",
      "Line": 162764,
      "Type": "package",
      "Package": "pillow",
      "Kind": "fixed",
      "Version": "8.1.2+dfsg-0.2",
      "BugNo": 989062
    },
    {
      "Original": "[buster] - pillow 5.4.1-2+deb10u3",
      "Line": 162765,
      "Type": "package",
      "Release": "buster",
      "Package": "pillow",
      "Kind": "fixed",
      "Version": "5.4.1-2+deb10u3"
    },
    {
      "Original": "[stretch] - pillow \u003cnot-affected\u003e (Vulnerable code introduced later)",
      "Line": 162766,
      "Type": "package",
      "Release": "stretch",
      "Package": "pillow",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced later"
    },
    {
      "Original": "NOTE: https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28678-fix-blp-dos",
      "Line": 162767,
      "Type": "NOTE",
      "Description": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28678-fix-blp-dos"
    },
    {
      "Original": "NOTE: https://github.com/python-pillow/Pillow/commit/496245aa4365d0827390bd0b6fbd11287453b3a1",
      "Line": 162768,
      "Type": "NOTE",
      "Description": "https://github.com/python-pillow/Pillow/commit/496245aa4365d0827390bd0b6fbd11287453b3a1"
    }
  ]
}