{
  "Header": {
    "Original": "CVE-2021-20231 (A flaw was found in gnutls. A use after free issue in client sending k ...)",
    "Line": 183697,
    "ID": "CVE-2021-20231",
    "Description": "(A flaw was found in gnutls. A use after free issue in client sending k ...)"
  },
  "Annotations": [
    {
      "Original": "- gnutls28 3.7.1-1",
      "Line": 183698,
      "Type": "package",
      "Package": "gnutls28",
      "Kind": "fixed",
      "Version": "3.7.1-1"
    },
    {
      "Original": "[buster] - gnutls28 3.6.7-4+deb10u7",
      "Line": 183699,
      "Type": "package",
      "Release": "buster",
      "Package": "gnutls28",
      "Kind": "fixed",
      "Version": "3.6.7-4+deb10u7"
    },
    {
      "Original": "[stretch] - gnutls28 \u003cnot-affected\u003e (Vulnerable code introduced later)",
      "Line": 183700,
      "Type": "package",
      "Release": "stretch",
      "Package": "gnutls28",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced later"
    },
    {
      "Original": "NOTE: https://www.gnutls.org/security-new.html#GNUTLS-SA-2021-03-10",
      "Line": 183701,
      "Type": "NOTE",
      "Description": "https://www.gnutls.org/security-new.html#GNUTLS-SA-2021-03-10"
    },
    {
      "Original": "NOTE: https://gitlab.com/gnutls/gnutls/-/issues/1151",
      "Line": 183702,
      "Type": "NOTE",
      "Description": "https://gitlab.com/gnutls/gnutls/-/issues/1151"
    }
  ]
}