{
  "Header": {
    "Original": "CVE-2019-10160 (A security regression of CVE-2019-9636 was discovered in python since  ...)",
    "Line": 291150,
    "ID": "CVE-2019-10160",
    "Description": "(A security regression of CVE-2019-9636 was discovered in python since  ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2280-1}",
      "Line": 291151,
      "Type": "xref",
      "Bugs": [
        "DLA-2280-1"
      ]
    },
    {
      "Original": "- python3.7 3.7.4~rc2-2",
      "Line": 291152,
      "Type": "package",
      "Package": "python3.7",
      "Kind": "fixed",
      "Version": "3.7.4~rc2-2"
    },
    {
      "Original": "[buster] - python3.7 3.7.3-2+deb10u1",
      "Line": 291153,
      "Type": "package",
      "Release": "buster",
      "Package": "python3.7",
      "Kind": "fixed",
      "Version": "3.7.3-2+deb10u1"
    },
    {
      "Original": "- python3.6 \u003cnot-affected\u003e (Fix for CVE-2019-9636 not applied)",
      "Line": 291154,
      "Type": "package",
      "Package": "python3.6",
      "Kind": "not-affected",
      "Description": "Fix for CVE-2019-9636 not applied"
    },
    {
      "Original": "- python3.5 \u003cremoved\u003e",
      "Line": 291155,
      "Type": "package",
      "Package": "python3.5",
      "Kind": "removed"
    },
    {
      "Original": "- python3.4 \u003cnot-affected\u003e (Vulnerable fix to regression introduced by fix for CVE-2019-9636 not applied)",
      "Line": 291156,
      "Type": "package",
      "Package": "python3.4",
      "Kind": "not-affected",
      "Description": "Vulnerable fix to regression introduced by fix for CVE-2019-9636 not applied"
    },
    {
      "Original": "- python2.7 2.7.16-3",
      "Line": 291157,
      "Type": "package",
      "Package": "python2.7",
      "Kind": "fixed",
      "Version": "2.7.16-3"
    },
    {
      "Original": "[buster] - python2.7 2.7.16-2+deb10u1",
      "Line": 291158,
      "Type": "package",
      "Release": "buster",
      "Package": "python2.7",
      "Kind": "fixed",
      "Version": "2.7.16-2+deb10u1"
    },
    {
      "Original": "[stretch] - python2.7 \u003cnot-affected\u003e (Incomplete fix for CVE-2019-9636 not applied)",
      "Line": 291159,
      "Type": "package",
      "Release": "stretch",
      "Package": "python2.7",
      "Kind": "not-affected",
      "Description": "Incomplete fix for CVE-2019-9636 not applied"
    },
    {
      "Original": "[jessie] - python2.7 \u003cnot-affected\u003e (Incomplete fix for CVE-2019-9636 not applied)",
      "Line": 291160,
      "Type": "package",
      "Release": "jessie",
      "Package": "python2.7",
      "Kind": "not-affected",
      "Description": "Incomplete fix for CVE-2019-9636 not applied"
    },
    {
      "Original": "NOTE: Introduced by: https://github.com/python/cpython/commit/d537ab0ff9767ef024f26246899728f0116b1ec3 (v3.8.0a4)",
      "Line": 291161,
      "Type": "NOTE",
      "Description": "Introduced by: https://github.com/python/cpython/commit/d537ab0ff9767ef024f26246899728f0116b1ec3 (v3.8.0a4)"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/python/cpython/commit/8d0ef0b5edeae52960c7ed05ae8a12388324f87e (v3.8.0b1)",
      "Line": 291162,
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/python/cpython/commit/8d0ef0b5edeae52960c7ed05ae8a12388324f87e (v3.8.0b1)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/250b62acc59921d399f0db47db3b462cd6037e09 (3.7)",
      "Line": 291163,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/250b62acc59921d399f0db47db3b462cd6037e09 (3.7)"
    },
    {
      "Original": "NOTE: https://bugs.python.org/issue36742",
      "Line": 291164,
      "Type": "NOTE",
      "Description": "https://bugs.python.org/issue36742"
    },
    {
      "Original": "NOTE: Patches for 2.7:",
      "Line": 291165,
      "Type": "NOTE",
      "Description": "Patches for 2.7:"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/98a4dcefbbc3bce5ab07e7c0830a183157250259",
      "Line": 291166,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/98a4dcefbbc3bce5ab07e7c0830a183157250259"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/f61599b050c621386a3fc6bc480359e2d3bb93de",
      "Line": 291167,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/f61599b050c621386a3fc6bc480359e2d3bb93de"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/2b578479b96aa3deeeb8bac313a02b5cf3cb1aff",
      "Line": 291168,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/2b578479b96aa3deeeb8bac313a02b5cf3cb1aff"
    }
  ]
}