{
  "Header": {
    "Original": "CVE-2018-11254 (An issue was discovered in PoDoFo 0.9.5. There is an Excessive Recursi ...)",
    "Line": 341901,
    "ID": "CVE-2018-11254",
    "Description": "(An issue was discovered in PoDoFo 0.9.5. There is an Excessive Recursi ...)"
  },
  "Annotations": [
    {
      "Original": "- libpodofo 0.9.6+dfsg-4 (low; bug #916585)",
      "Line": 341902,
      "Type": "package",
      "Package": "libpodofo",
      "Kind": "fixed",
      "Version": "0.9.6+dfsg-4",
      "Severity": "low",
      "BugNo": 916585
    },
    {
      "Original": "[stretch] - libpodofo \u003cno-dsa\u003e (Minor issue)",
      "Line": 341903,
      "Type": "package",
      "Release": "stretch",
      "Package": "libpodofo",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[jessie] - libpodofo \u003cno-dsa\u003e (Minor issue)",
      "Line": 341904,
      "Type": "package",
      "Release": "jessie",
      "Package": "libpodofo",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[wheezy] - libpodofo \u003cno-dsa\u003e (Minor issue)",
      "Line": 341905,
      "Type": "package",
      "Release": "wheezy",
      "Package": "libpodofo",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1576174",
      "Line": 341906,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=1576174"
    },
    {
      "Original": "NOTE: https://sourceforge.net/p/podofo/tickets/19",
      "Line": 341907,
      "Type": "NOTE",
      "Description": "https://sourceforge.net/p/podofo/tickets/19"
    },
    {
      "Original": "NOTE: https://sourceforge.net/p/podofo/code/1941",
      "Line": 341908,
      "Type": "NOTE",
      "Description": "https://sourceforge.net/p/podofo/code/1941"
    }
  ]
}