{
  "Header": {
    "Original": "CVE-2021-30154 (An issue was discovered in MediaWiki before 1.31.12 and 1.32.x through ...)",
    "Line": 154404,
    "ID": "CVE-2021-30154",
    "Description": "(An issue was discovered in MediaWiki before 1.31.12 and 1.32.x through ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4889-1}",
      "Line": 154405,
      "Type": "xref",
      "Bugs": [
        "DSA-4889-1"
      ]
    },
    {
      "Original": "- mediawiki 1:1.35.2-1",
      "Line": 154406,
      "Type": "package",
      "Package": "mediawiki",
      "Kind": "fixed",
      "Version": "1:1.35.2-1"
    },
    {
      "Original": "[stretch] - mediawiki \u003cnot-affected\u003e (Vulnerable code introduced later)",
      "Line": 154407,
      "Type": "package",
      "Release": "stretch",
      "Package": "mediawiki",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced later"
    },
    {
      "Original": "NOTE: https://phabricator.wikimedia.org/T278014",
      "Line": 154408,
      "Type": "NOTE",
      "Description": "https://phabricator.wikimedia.org/T278014"
    },
    {
      "Original": "NOTE: https://gerrit.wikimedia.org/r/c/mediawiki/core/+/674083/",
      "Line": 154409,
      "Type": "NOTE",
      "Description": "https://gerrit.wikimedia.org/r/c/mediawiki/core/+/674083/"
    }
  ]
}