{
  "Header": {
    "Original": "CVE-2020-27675 (An issue was discovered in the Linux kernel through 5.9.1, as used wit ...)",
    "Line": 194419,
    "ID": "CVE-2020-27675",
    "Description": "(An issue was discovered in the Linux kernel through 5.9.1, as used wit ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2494-1 DLA-2483-1}",
      "Line": 194420,
      "Type": "xref",
      "Bugs": [
        "DLA-2494-1",
        "DLA-2483-1"
      ]
    },
    {
      "Original": "- linux 5.9.6-1",
      "Line": 194421,
      "Type": "package",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "5.9.6-1"
    },
    {
      "Original": "[buster] - linux 4.19.160-1",
      "Line": 194422,
      "Type": "package",
      "Release": "buster",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "4.19.160-1"
    },
    {
      "Original": "NOTE: https://xenbits.xen.org/xsa/advisory-331.html",
      "Line": 194423,
      "Type": "NOTE",
      "Description": "https://xenbits.xen.org/xsa/advisory-331.html"
    }
  ]
}