{
  "Header": {
    "Original": "CVE-2022-3597 (LibTIFF 4.4.0 has an out-of-bounds write in _TIFFmemcpy in libtiff/tif ...)",
    "Line": 46699,
    "ID": "CVE-2022-3597",
    "Description": "(LibTIFF 4.4.0 has an out-of-bounds write in _TIFFmemcpy in libtiff/tif ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-5333-1 DLA-3278-1}",
      "Line": 46700,
      "Type": "xref",
      "Bugs": [
        "DSA-5333-1",
        "DLA-3278-1"
      ]
    },
    {
      "Original": "- tiff 4.4.0-5 (bug #1022555)",
      "Line": 46701,
      "Type": "package",
      "Package": "tiff",
      "Kind": "fixed",
      "Version": "4.4.0-5",
      "BugNo": 1022555
    },
    {
      "Original": "NOTE: https://gitlab.com/libtiff/libtiff/-/commit/236b7191f04c60d09ee836ae13b50f812c841047",
      "Line": 46702,
      "Type": "NOTE",
      "Description": "https://gitlab.com/libtiff/libtiff/-/commit/236b7191f04c60d09ee836ae13b50f812c841047"
    },
    {
      "Original": "NOTE: https://gitlab.com/libtiff/libtiff/-/issues/413",
      "Line": 46703,
      "Type": "NOTE",
      "Description": "https://gitlab.com/libtiff/libtiff/-/issues/413"
    }
  ]
}