{
  "Header": {
    "Original": "CVE-2021-20199 (Rootless containers run with Podman, receive all traffic with a source ...)",
    "Line": 183228,
    "ID": "CVE-2021-20199",
    "Description": "(Rootless containers run with Podman, receive all traffic with a source ...)"
  },
  "Annotations": [
    {
      "Original": "- libpod 3.0.0~rc2+dfsg1-2",
      "Line": 183229,
      "Type": "package",
      "Package": "libpod",
      "Kind": "fixed",
      "Version": "3.0.0~rc2+dfsg1-2"
    },
    {
      "Original": "- rootlesskit 0.12.0-1",
      "Line": 183230,
      "Type": "package",
      "Package": "rootlesskit",
      "Kind": "fixed",
      "Version": "0.12.0-1"
    },
    {
      "Original": "NOTE: https://github.com/containers/podman/issues/5138",
      "Line": 183231,
      "Type": "NOTE",
      "Description": "https://github.com/containers/podman/issues/5138"
    },
    {
      "Original": "NOTE: https://github.com/containers/podman/pull/9052",
      "Line": 183232,
      "Type": "NOTE",
      "Description": "https://github.com/containers/podman/pull/9052"
    },
    {
      "Original": "NOTE: https://github.com/rootless-containers/rootlesskit/pull/206",
      "Line": 183233,
      "Type": "NOTE",
      "Description": "https://github.com/rootless-containers/rootlesskit/pull/206"
    },
    {
      "Original": "NOTE: For Podman v3.0: https://github.com/containers/podman/pull/9225 (v3.0.0-rc3)",
      "Line": 183234,
      "Type": "NOTE",
      "Description": "For Podman v3.0: https://github.com/containers/podman/pull/9225 (v3.0.0-rc3)"
    },
    {
      "Original": "NOTE: Issue in podman was fixed by linking against rootlesskit 0.12, and Debian updated",
      "Line": 183235,
      "Type": "NOTE",
      "Description": "Issue in podman was fixed by linking against rootlesskit 0.12, and Debian updated"
    },
    {
      "Original": "NOTE: ahead of time",
      "Line": 183236,
      "Type": "NOTE",
      "Description": "ahead of time"
    }
  ]
}