{
  "Header": {
    "Original": "CVE-2013-2027 (Jython 2.2.1 uses the current umask to set the privileges of the class ...)",
    "Line": 519521,
    "ID": "CVE-2013-2027",
    "Description": "(Jython 2.2.1 uses the current umask to set the privileges of the class ...)"
  },
  "Annotations": [
    {
      "Original": "[experimental] - jython 2.7.0+repack-1",
      "Line": 519522,
      "Type": "package",
      "Release": "experimental",
      "Package": "jython",
      "Kind": "fixed",
      "Version": "2.7.0+repack-1"
    },
    {
      "Original": "- jython 2.7.1+repack-1 (low; bug #777079)",
      "Line": 519523,
      "Type": "package",
      "Package": "jython",
      "Kind": "fixed",
      "Version": "2.7.1+repack-1",
      "Severity": "low",
      "BugNo": 777079
    },
    {
      "Original": "[stretch] - jython \u003cignored\u003e (Minor issue)",
      "Line": 519524,
      "Type": "package",
      "Release": "stretch",
      "Package": "jython",
      "Kind": "ignored",
      "Description": "Minor issue"
    },
    {
      "Original": "[jessie] - jython \u003cignored\u003e (Minor issue)",
      "Line": 519525,
      "Type": "package",
      "Release": "jessie",
      "Package": "jython",
      "Kind": "ignored",
      "Description": "Minor issue"
    },
    {
      "Original": "[wheezy] - jython \u003cno-dsa\u003e (Minor issue)",
      "Line": 519526,
      "Type": "package",
      "Release": "wheezy",
      "Package": "jython",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[squeeze] - jython \u003cno-dsa\u003e (Minor issue)",
      "Line": 519527,
      "Type": "package",
      "Release": "squeeze",
      "Package": "jython",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: http://bugs.jython.org/issue2044",
      "Line": 519528,
      "Type": "NOTE",
      "Description": "http://bugs.jython.org/issue2044"
    },
    {
      "Original": "NOTE: The original issue seem addressed in 2.7.0+repack-1, but still files",
      "Line": 519529,
      "Type": "NOTE",
      "Description": "The original issue seem addressed in 2.7.0+repack-1, but still files"
    },
    {
      "Original": "NOTE: might be created/written to /usr/share/jython/cachedir/packages",
      "Line": 519530,
      "Type": "NOTE",
      "Description": "might be created/written to /usr/share/jython/cachedir/packages"
    },
    {
      "Original": "NOTE: which should not be in /usr beeing a cachedir.",
      "Line": 519531,
      "Type": "NOTE",
      "Description": "which should not be in /usr beeing a cachedir."
    }
  ]
}