{
  "Header": {
    "Original": "CVE-2021-23166 (A sandboxing issue in Odoo Community 15.0 and earlier and Odoo Enterpr ...)",
    "Line": 109712,
    "ID": "CVE-2021-23166",
    "Description": "(A sandboxing issue in Odoo Community 15.0 and earlier and Odoo Enterpr ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-5399-1}",
      "Line": 109713,
      "Type": "xref",
      "Bugs": [
        "DSA-5399-1"
      ]
    },
    {
      "Original": "- odoo \u003cunfixed\u003e (bug #1035953)",
      "Line": 109714,
      "Type": "package",
      "Package": "odoo",
      "Kind": "unfixed",
      "BugNo": 1035953
    },
    {
      "Original": "NOTE: https://github.com/odoo/odoo/issues/107687",
      "Line": 109715,
      "Type": "NOTE",
      "Description": "https://github.com/odoo/odoo/issues/107687"
    },
    {
      "Original": "NOTE: 14.0 patch at https://github.com/odoo/odoo/commit/1f1e03ff29f711dd26cfbcadc60b7d03fdb59ed7",
      "Line": 109716,
      "Type": "NOTE",
      "Description": "14.0 patch at https://github.com/odoo/odoo/commit/1f1e03ff29f711dd26cfbcadc60b7d03fdb59ed7"
    }
  ]
}