{
  "Header": {
    "Original": "CVE-2019-17626 (ReportLab through 3.5.26 allows remote code execution because of toCol ...)",
    "Line": 270822,
    "ID": "CVE-2019-17626",
    "Description": "(ReportLab through 3.5.26 allows remote code execution because of toCol ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4663-1 DLA-2112-1}",
      "Line": 270823,
      "Type": "xref",
      "Bugs": [
        "DSA-4663-1",
        "DLA-2112-1"
      ]
    },
    {
      "Original": "- python-reportlab 3.5.34-1 (bug #942763)",
      "Line": 270824,
      "Type": "package",
      "Package": "python-reportlab",
      "Kind": "fixed",
      "Version": "3.5.34-1",
      "BugNo": 942763
    },
    {
      "Original": "NOTE: https://bitbucket.org/rptlab/reportlab/issues/199/eval-in-colorspy-leads-to-remote-code",
      "Line": 270825,
      "Type": "NOTE",
      "Description": "https://bitbucket.org/rptlab/reportlab/issues/199/eval-in-colorspy-leads-to-remote-code"
    },
    {
      "Original": "NOTE: Minimal patch in https://bitbucket.org/rptlab/reportlab/issues/199/eval-in-colorspy-leads-to-remote-code#comment-55887892",
      "Line": 270826,
      "Type": "NOTE",
      "Description": "Minimal patch in https://bitbucket.org/rptlab/reportlab/issues/199/eval-in-colorspy-leads-to-remote-code#comment-55887892"
    },
    {
      "Original": "NOTE: but upstream did make the bugreport private.",
      "Line": 270827,
      "Type": "NOTE",
      "Description": "but upstream did make the bugreport private."
    }
  ]
}